---
- name: Gather EC2 facts
  hosts: localhost
  gather_facts: false

  vars:
    ec2_region: us-west-2

  tasks:
  - name: Gather EC2 facts
    ec2_instance_facts:
      region: "{{ ec2_region }}"
      filters: 
        key-name: thaumos
        instance-state: running
    register: ec2

  # - name: Output facts
  #   debug:
  #     var: ec2
  - name: Terminate instances
    ec2:
      state: absent
      region: "{{ ec2_region }}"
      instance_ids: "{{ item.instance_id }}"
    with_items: "{{ ec2.instances }}"