---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: false

  vars:
    region: us-west-1
    count: 1
    env: Production
    ami: ami-af4333cf #Centos 7 ami
    type: t2.micro

  tasks:
  - name: Launch!
    ec2:
      keypair: thaumos
      group: thaumos
      image: "{{ ami }}"
      type: "{{ type }}"
      region: "{{ region }}"
      instance_tags:
          Name: "thaumos"
          env: "{{ env }}"
      count: "{{ count }}"
      wait: true
